.PHONY: test coverage

test:
	go vet ./...
	go test -race ./...
	go tool workflowcheck -config workflowcheck.config.yaml ./...

coverage:
	go test -coverprofile=coverage.out ./...
	go tool cover -func=coverage.out
	go tool cover -html=coverage.out -o coverage.html
