package workflows

import (
	"fmt"
	"github.com/bcc-code/bccm-flows/utils/wfutils"
	"strings"
	"time"

	"github.com/bcc-code/bccm-flows/activities"
	"github.com/bcc-code/bccm-flows/activities/vidispine"
	"github.com/bcc-code/bccm-flows/utils"
	"go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/workflow"
)

type ImportSubtitlesFromSubtransInput struct {
	VXID string
}

func ImportSubtitlesFromSubtrans(
	ctx workflow.Context,
	params ImportSubtitlesFromSubtransInput,
) error {
	logger := workflow.GetLogger(ctx)

	options := workflow.ActivityOptions{
		RetryPolicy: &temporal.RetryPolicy{
			InitialInterval:        time.Minute * 3,
			MaximumAttempts:        10,
			MaximumInterval:        time.Hour * 1,
			NonRetryableErrorTypes: []string{},
		},
		StartToCloseTimeout:    time.Hour * 4,
		ScheduleToCloseTimeout: time.Hour * 48,
		HeartbeatTimeout:       time.Minute * 5,
		TaskQueue:              utils.GetQueue(),
	}

	ctx = workflow.WithActivityOptions(ctx, options)

	logger.Info("Starting sub import flow")

	input := activities.GetSubtransIDInput{
		VXID:     params.VXID,
		NoSubsOK: true,
	}

	subtransIDResponse := &activities.GetSubtransIDOutput{}
	err := workflow.ExecuteActivity(ctx, activities.GetSubtransIDActivity, input).Get(ctx, subtransIDResponse)
	if err != nil {
		return err
	}

	outputPath, _ := wfutils.GetWorkflowAuxOutputFolder(ctx)

	subsList := map[string]string{}
	err = workflow.ExecuteActivity(ctx, activities.GetSubtitlesActivity, activities.GetSubtitlesInput{
		SubtransID:        subtransIDResponse.SubtransID,
		Format:            "srt",
		ApprovedOnly:      false,
		DestinationFolder: outputPath,
		//FilePrefix:        "subs_", <-- Generated by subtrans if empty
	}).Get(ctx, &subsList)
	if err != nil {
		return err
	}

	var futures []workflow.Future
	for lang, sub := range subsList {
		lang = strings.ToLower(lang)

		future := workflow.ExecuteActivity(ctx, vidispine.ImportFileAsSidecarActivity, vidispine.ImportSubtitleAsSidecarParams{
			AssetID:  params.VXID,
			Language: lang,
			FilePath: sub,
		})

		futures = append(futures, future)

		future = workflow.ExecuteActivity(ctx, vidispine.ImportFileAsShapeActivity, vidispine.ImportFileAsShapeParams{
			AssetID:  params.VXID,
			FilePath: sub,
			ShapeTag: fmt.Sprintf("sub_%s_%s", lang, "srt"),
		})

		futures = append(futures, future)
	}

	for _, future := range futures {
		err = future.Get(ctx, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
